### ISSUE TITLE
Provider Crash When Attempting to Read Missing Variable Resource

### ISSUE THREAD

**Issue by evan-cleary** [OctopusDeployLabs/terraform-provider-octopusdeploy#153]
**Describe the bug**
The provider will crash if a variable managed by the terraform provider is deleted outside of terraform.

**Steps to reproduce**
1. Create a Library variable set
2. Create a variable in the created variable set
3. Apply
4. Manually delete the variable
5. Run Plan (crashes)

**Expected behavior**
Provider should recognize resource is missing and create it.

**Logs and other supporting information**
```go
octopusdeploy_library_variable_set.this: Refreshing state... [id=LibraryVariableSets-1]
octopusdeploy_variable.this: Refreshing state... [id=47b0a08b-9bae-4034-ade4-7cae4ce915d8]

Error: rpc error: code = Unavailable desc = transport is closing


panic: runtime error: invalid memory address or nil pointer dereference
2021-04-06T20:21:36.781-0400 [DEBUG] plugin.terraform-provider-octopusdeploy_v0.7.16: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa812a6]
2021-04-06T20:21:36.781-0400 [DEBUG] plugin.terraform-provider-octopusdeploy_v0.7.16: 
2021-04-06T20:21:36.781-0400 [DEBUG] plugin.terraform-provider-octopusdeploy_v0.7.16: goroutine 99 [running]:
2021-04-06T20:21:36.781-0400 [DEBUG] plugin.terraform-provider-octopusdeploy_v0.7.16: github.com/OctopusDeploy/terraform-provider-octopusdeploy/octopusdeploy.setVariable(0xf79520, 0xc00084cf60, 0xc0004bec00, 0x0, 0xc00072e9c0, 0x17)
2021-04-06T20:21:36.781-0400 [DEBUG] plugin.terraform-provider-octopusdeploy_v0.7.16:   github.com/OctopusDeploy/terraform-provider-octopusdeploy/octopusdeploy/schema_variable.go:121 +0x26
2021-04-06T20:21:36.781-0400 [DEBUG] plugin.terraform-provider-octopusdeploy_v0.7.16: github.com/OctopusDeploy/terraform-provider-octopusdeploy/octopusdeploy.resourceVariableRead(0xf79520, 0xc00084cf60, 0xc0004bec00, 0xcef3c0, 0xc0001fc000, 0xc000352320, 0xc0000cb8f0, 0x40e118)
2021-04-06T20:21:36.781-0400 [DEBUG] plugin.terraform-provider-octopusdeploy_v0.7.16:   github.com/OctopusDeploy/terraform-provider-octopusdeploy/octopusdeploy/resource_variable.go:58 +0x4a9
2021-04-06T20:21:36.781-0400 [DEBUG] plugin.terraform-provider-octopusdeploy_v0.7.16: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc000365ea0, 0xf794a0, 0xc000836400, 0xc0004bec00, 0xcef3c0, 0xc0001fc000, 0x0, 0x0, 0x0)
2021-04-06T20:21:36.781-0400 [DEBUG] plugin.terraform-provider-octopusdeploy_v0.7.16:   github.com/hashicorp/terraform-plugin-sdk/v2@v2.5.0/helper/schema/resource.go:347 +0x17c
2021-04-06T20:21:36.781-0400 [DEBUG] plugin.terraform-provider-octopusdeploy_v0.7.16: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000365ea0, 0xf794a0, 0xc000836400, 0xc0004c0cb0, 0xcef3c0, 0xc0001fc000, 0xc000406e10, 0x0, 0x0, 0x0)
2021-04-06T20:21:36.781-0400 [DEBUG] plugin.terraform-provider-octopusdeploy_v0.7.16:   github.com/hashicorp/terraform-plugin-sdk/v2@v2.5.0/helper/schema/resource.go:624 +0x1cb
2021-04-06T20:21:36.781-0400 [DEBUG] plugin.terraform-provider-octopusdeploy_v0.7.16: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc0005acac0, 0xf794a0, 0xc000836400, 0xc000836440, 0xc000836400, 0xde0a80, 0xe16280)
2021-04-06T20:21:36.781-0400 [DEBUG] plugin.terraform-provider-octopusdeploy_v0.7.16:   github.com/hashicorp/terraform-plugin-sdk/v2@v2.5.0/helper/schema/grpc_provider.go:575 +0x43b
2021-04-06T20:21:36.781-0400 [DEBUG] plugin.terraform-provider-octopusdeploy_v0.7.16: github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadResource(0xc00000df00, 0xf794a0, 0xc000836400, 0xc00084cc00, 0xc00000df00, 0xc00059be00, 0xc0005cdba0)
2021-04-06T20:21:36.781-0400 [DEBUG] plugin.terraform-provider-octopusdeploy_v0.7.16:   github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/server/server.go:298 +0x105
2021-04-06T20:21:36.781-0400 [DEBUG] plugin.terraform-provider-octopusdeploy_v0.7.16: github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0xe16280, 0xc00000df00, 0xf79560, 0xc00059be00, 0xc00084cba0, 0x0, 0xf79560, 0xc00059be00, 0xc00072c200, 0x100)
2021-04-06T20:21:36.781-0400 [DEBUG] plugin.terraform-provider-octopusdeploy_v0.7.16:   github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x214
2021-04-06T20:21:36.781-0400 [DEBUG] plugin.terraform-provider-octopusdeploy_v0.7.16: google.golang.org/grpc.(*Server).processUnaryRPC(0xc00042a540, 0xf82ba0, 0xc000093980, 0xc0005d8900, 0xc00061a5a0, 0x14711f0, 0x0, 0x0, 0x0)
2021-04-06T20:21:36.781-0400 [DEBUG] plugin.terraform-provider-octopusdeploy_v0.7.16:   google.golang.org/grpc@v1.36.1/server.go:1217 +0x522
2021-04-06T20:21:36.781-0400 [DEBUG] plugin.terraform-provider-octopusdeploy_v0.7.16: google.golang.org/grpc.(*Server).handleStream(0xc00042a540, 0xf82ba0, 0xc000093980, 0xc0005d8900, 0x0)
2021-04-06T20:21:36.781-0400 [DEBUG] plugin.terraform-provider-octopusdeploy_v0.7.16:   google.golang.org/grpc@v1.36.1/server.go:1540 +0xd05
2021-04-06T20:21:36.781-0400 [DEBUG] plugin.terraform-provider-octopusdeploy_v0.7.16: google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0000ae200, 0xc00042a540, 0xf82ba0, 0xc000093980, 0xc0005d8900)
2021-04-06T20:21:36.781-0400 [DEBUG] plugin.terraform-provider-octopusdeploy_v0.7.16:   google.golang.org/grpc@v1.36.1/server.go:878 +0xa5
2021-04-06T20:21:36.781-0400 [DEBUG] plugin.terraform-provider-octopusdeploy_v0.7.16: created by google.golang.org/grpc.(*Server).serveStreams.func1
2021-04-06T20:21:36.781-0400 [DEBUG] plugin.terraform-provider-octopusdeploy_v0.7.16:   google.golang.org/grpc@v1.36.1/server.go:876 +0x1fd
2021/04/06 20:21:36 [TRACE] vertex "octopusdeploy_variable.this": visit complete
2021-04-06T20:21:36.782-0400 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2021/04/06 20:21:36 [TRACE] vertex "octopusdeploy_variable.this": dynamic subgraph encountered errors
2021/04/06 20:21:36 [TRACE] vertex "octopusdeploy_variable.this": visit complete
2021/04/06 20:21:36 [TRACE] vertex "octopusdeploy_variable.this (expand)": dynamic subgraph encountered errors
2021/04/06 20:21:36 [TRACE] vertex "octopusdeploy_variable.this (expand)": visit complete
2021/04/06 20:21:36 [TRACE] dag/walk: upstream of "meta.count-boundary (EachMode fixup)" errored, so skipping
2021-04-06T20:21:36.782-0400 [DEBUG] plugin: plugin process exited: path=.terraform/providers/registry.terraform.io/octopusdeploylabs/octopusdeploy/0.7.16/linux_amd64/terraform-provider-octopusdeploy_v0.7.16 pid=5931 error="exit status 2"
2021/04/06 20:21:36 [TRACE] dag/walk: upstream of "provider[\"registry.terraform.io/octopusdeploylabs/octopusdeploy\"] (close)" errored, so skipping
2021/04/06 20:21:36 [TRACE] dag/walk: upstream of "root" errored, so skipping
2021/04/06 20:21:36 [INFO] backend/local: plan operation completed
2021/04/06 20:21:36 [TRACE] statemgr.Filesystem: removing lock metadata file .terraform.tfstate.lock.info
2021/04/06 20:21:36 [TRACE] statemgr.Filesystem: unlocking terraform.tfstate using fcntl flock
2021-04-06T20:21:36.783-0400 [DEBUG] plugin: plugin exited
```

**Screenshots**

**Environment and versions:**
- OS: Any
- Octopus Server Version: Any
- Terraform Version: 0.14.7
- Octopus Terraform Provider Version: 0.7.0+

**Additional context**
RCA: Behavior is a result of commit c11f9170cc9741c97057af495f5d8bb7b88faf08 due to the GetByID function of the VariableService in the go api not returning a 404 when a variable is missing. Function works as expected if the project the variable is tied to is manually deleted. 

This can be fixed by either adding back the 
```go
	if variable == nil {
		d.SetId("")
		return nil
	}
```
check, or by changing the Not Found behavior of the GetByID function in the go-octopusdeploy api:

https://github.com/OctopusDeploy/go-octopusdeploy/blob/e4c34bb321928368175aee8eb9775858df0ec98d/octopusdeploy/variable_service.go#L80

to
```go
	return nil, APIError{
		StatusCode:   404,
		ErrorMessage: fmt.Sprintf("Variable %s could not be found in project %s.", variableID, projectID),
	}
```

**Comment by jbristowe** [comment]
Hey @evan-cleary. 👋 I've just shipped a new release that updates variable scopes. I'm not sure what impact it might have on this issue, but please let me know it's resolved. Thanks!
