### ISSUE TITLE
Provider fails on deployment_step after upgrading

### ISSUE THREAD

**Issue by ecca** [OctopusDeployLabs/terraform-provider-octopusdeploy#172]
**Describe the bug**
After upgrading provider seems to quit on deployment_step

**Steps to reproduce**

**Expected behavior**
Not throwing errors

**Logs and other supporting information**
```javascript
╷
│ Error: Request cancelled
│ 
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵
╷
│ Error: Request cancelled
│ 
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).UpgradeResourceState call. The plugin logs may
│ contain more details.
╵
╷
│ Error: Request cancelled
│ 
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Request cancelled
│ 
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Request cancelled
│ 
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Request cancelled
│ 
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Request cancelled
│ 
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Request cancelled
│ 
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).UpgradeResourceState call. The plugin logs may
│ contain more details.
╵
╷
│ Error: Request cancelled
│ 
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Request cancelled
│ 
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Request cancelled
│ 
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵
╷
│ Error: Request cancelled
│ 
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Request cancelled
│ 
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵
╷
│ Error: Request cancelled
│ 
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).UpgradeResourceState call. The plugin logs may
│ contain more details.
╵
╷
│ Error: Request cancelled
│ 
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Request cancelled
│ 
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵
╷
│ Error: Request cancelled
│ 
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).UpgradeResourceState call. The plugin logs may
│ contain more details.
╵
╷
│ Error: Request cancelled
│ 
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵

Stack trace from the terraform-provider-octopusdeploy_v0.7.29 plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 134 [running]:
github.com/OctopusDeploy/terraform-provider-octopusdeploy/octopusdeploy.expandVariableScope(0xd27460, 0xc0008d3fa0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/OctopusDeploy/terraform-provider-octopusdeploy/octopusdeploy/schema_variable_scope.go:18 +0x96b
github.com/OctopusDeploy/terraform-provider-octopusdeploy/octopusdeploy.expandVariable(0xc000a47f00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/OctopusDeploy/terraform-provider-octopusdeploy/octopusdeploy/schema_variable.go:33 +0x805
github.com/OctopusDeploy/terraform-provider-octopusdeploy/octopusdeploy.resourceVariableUpdate(0xf9ca80, 0xc000cbe660, 0xc000a47f00, 0xd0adc0, 0xc0001aa280, 0xc0009fedb0, 0x93a46a, 0xc00076fde0)
	github.com/OctopusDeploy/terraform-provider-octopusdeploy/octopusdeploy/resource_variable.go:106 +0x1b8
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0xc0002240e0, 0xf9ca00, 0xc000913a80, 0xc000a47f00, 0xd0adc0, 0xc0001aa280, 0x0, 0x0, 0x0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.5.0/helper/schema/resource.go:364 +0x17c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0002240e0, 0xf9ca00, 0xc000913a80, 0xc00017be30, 0xc00076fde0, 0xd0adc0, 0xc0001aa280, 0x0, 0x0, 0x0, ...)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.5.0/helper/schema/resource.go:464 +0x390
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000352960, 0xf9ca00, 0xc000913a80, 0xc000b9f1d0, 0xc000913a80, 0x0, 0xfa84c0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.5.0/helper/schema/grpc_provider.go:955 +0x8cf
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ApplyResourceChange(0xc0008bc9a0, 0xf9ca00, 0xc000913a80, 0xc00017bd50, 0xc0008bc9a0, 0xc0006afe90, 0xc0006ceba0)
	github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/server/server.go:332 +0xae
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0xe34420, 0xc0008bc9a0, 0xf9cac0, 0xc0006afe90, 0xc00056fda0, 0x0, 0xf9cac0, 0xc0006afe90, 0xc000471200, 0x442)
	github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0003968c0, 0xfa6340, 0xc000001c80, 0xc0006f7c20, 0xc0007184e0, 0x14a7c20, 0x0, 0x0, 0x0)
	google.golang.org/grpc@v1.37.0/server.go:1217 +0x522
google.golang.org/grpc.(*Server).handleStream(0xc0003968c0, 0xfa6340, 0xc000001c80, 0xc0006f7c20, 0x0)
	google.golang.org/grpc@v1.37.0/server.go:1540 +0xd05
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc00003c1b0, 0xc0003968c0, 0xfa6340, 0xc000001c80, 0xc0006f7c20)
	google.golang.org/grpc@v1.37.0/server.go:878 +0xa5
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.37.0/server.go:876 +0x1fd

Error: The terraform-provider-octopusdeploy_v0.7.29 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

Error: Terraform exited with code 1.
Error: Process completed with exit code 1.
```

**Environment and versions:**
- OS: Windows
- Octopus Server Version: 2020.6.4855
- Terraform Version: 0.14.19
- Octopus Terraform Provider Version: 0.7.29

**Additional context**

**Comment by jbristowe** [comment]
Do you have a snippet of your configuration for the `octopusdeploy_variable` resource?

**Comment by ecca** [comment]
Terraform plan executed without any issues. But apply fails.

Snippet: 
```javascript
resource "octopusdeploy_variable" "ov" {
  name       = var.name
  project_id = var.project
  type       = var.type
  value      = var.value

  scope {
    environments = var.environments
  }
}

```

Plan output

`Plan: 0 to add, 52 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────

Note: You didn't use the -out option to save this plan, so Terraform can't
guarantee to take exactly these actions if you run "terraform apply" now.
Releasing state lock. This may take a few moments...`

**Comment by jbristowe** [comment]
Discovered a regression in the Go API client. Fixing now.

**Comment by jbristowe** [comment]
Issued a new release for a regression that was introduced in the Go API client. Please let me know how that goes. 👍

**Comment by ecca** [comment]
Thanks for swift replies, unfortunately it still occurs. I switched `project_id` to `owner_id` on `octopusdeploy_variable`

Snippet
```javascript
resource "octopusdeploy_variable" "ov" {
  name     = var.name
  owner_id = var.project
  type     = var.type
  value    = var.value

  scope {
    environments = var.environments
  }
}
```

```javascript
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more
│ details.
╵
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more
│ details.
╵
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more
│ details.
╵
╷
│ Error: Request cancelled
│ 
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more
│ details.
╵
Releasing state lock. This may take a few moments...

Stack trace from the terraform-provider-octopusdeploy_v0.7.31 plugin:

panic: interface conversion: error is octopusdeploy.errInvalidvariableServiceParameter, not *octopusdeploy.APIError

goroutine 130 [running]:
github.com/OctopusDeploy/terraform-provider-octopusdeploy/octopusdeploy.resourceVariableRead(0xf9b1a0, 0xc000bbecc0, 0xc000ba0b80, 0xd09ce0, 0xc0002dfb80, 0xc0006b1130, 0xc0007138f0, 0x40e118)
	github.com/OctopusDeploy/terraform-provider-octopusdeploy/octopusdeploy/resource_variable.go:50 +0x916
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc000142b60, 0xf9b120, 0xc00068ae00, 0xc000ba0b80, 0xd09ce0, 0xc0002dfb80, 0x0, 0x0, 0x0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.5.0/helper/schema/resource.go:347 +0x17c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000142b60, 0xf9b120, 0xc00068ae00, 0xc0000fa1c0, 0xd09ce0, 0xc0002dfb80, 0xc0006d8070, 0x0, 0x0, 0x0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.5.0/helper/schema/resource.go:624 +0x1cb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00032acc0, 0xf9b120, 0xc00068ae00, 0xc00068ae40, 0xc00068ae00, 0xdfd260, 0xe334a0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.5.0/helper/schema/grpc_provider.go:575 +0x43b
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadResource(0xc00000ca80, 0xf9b120, 0xc00068ae00, 0xc000bbe8a0, 0xc00000ca80, 0xc000692fc0, 0xc00030dba0)
	github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/server/server.go:298 +0x105
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0xe334a0, 0xc00000ca80, 0xf9b1e0, 0xc000692fc0, 0xc000bbe840, 0x0, 0xf9b1e0, 0xc000692fc0, 0xc0002c7040, 0x13d)
	github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00036e700, 0xfa4a60, 0xc0002fd800, 0xc00068f440, 0xc0004dc4b0, 0x14a6bf0, 0x0, 0x0, 0x0)
	google.golang.org/grpc@v1.37.0/server.go:1217 +0x522
google.golang.org/grpc.(*Server).handleStream(0xc00036e700, 0xfa4a60, 0xc0002fd800, 0xc00068f440, 0x0)
	google.golang.org/grpc@v1.37.0/server.go:1540 +0xd05
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0002ba1b0, 0xc00036e700, 0xfa4a60, 0xc0002fd800, 0xc00068f440)
	google.golang.org/grpc@v1.37.0/server.go:878 +0xa5
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.37.0/server.go:876 +0x1fd

Error: The terraform-provider-octopusdeploy_v0.7.31 plugin crashed!
```

**Comment by jbristowe** [comment]
It appears that the Go API client library reference is out-of-date.

**Comment by ecca** [comment]
Okey, is it anything on my end ?

**Comment by berengamble** [comment]
I don't think so, @ecca. I'm getting the exact same error when trying to plan after changing `project_id` to `owner_id`. 

Using Terraform 0.15.

**Comment by jbristowe** [comment]
The schema property (`project_id`) was renamed without deprecated it beforehand. 😞 This change invalidated `project_id` in the underlying state.

The next release will resolve this behaviour.

**Comment by jbristowe** [comment]
A new release is available which should resolve this behaviour. Please let me know how it goes.

**Comment by ecca** [comment]
Thank you for the update, seems like there's an issue in the upgrade state

```javascript
│ Error: Request cancelled
│ 
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Request cancelled
│ 
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵

Stack trace from the terraform-provider-octopusdeploy_v0.7.32 plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 47 [running]:
github.com/OctopusDeploy/terraform-provider-octopusdeploy/octopusdeploy.expandVariableScope(0xd26300, 0xc0008c4740, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/OctopusDeploy/terraform-provider-octopusdeploy/octopusdeploy/schema_variable_scope.go:18 +0x4a7
github.com/OctopusDeploy/terraform-provider-octopusdeploy/octopusdeploy.expandVariable(0xc000631780, 0x0)
	github.com/OctopusDeploy/terraform-provider-octopusdeploy/octopusdeploy/schema_variable.go:33 +0x8b8
github.com/OctopusDeploy/terraform-provider-octopusdeploy/octopusdeploy.resourceVariableUpdate(0xf9b260, 0xc00071fc80, 0xc000631780, 0xd09ce0, 0xc0001aa000, 0x0, 0x0, 0x0)
	github.com/OctopusDeploy/terraform-provider-octopusdeploy/octopusdeploy/resource_variable.go:143 +0x23f
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0xc00054c620, 0xf9b1e0, 0xc000611580, 0xc000631780, 0xd09ce0, 0xc0001aa000, 0x0, 0x0, 0x0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.5.0/helper/schema/resource.go:364 +0x17c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc00054c620, 0xf9b1e0, 0xc000611580, 0xc00011fce0, 0xc0005b75a0, 0xd09ce0, 0xc0001aa000, 0x0, 0x0, 0x0, ...)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.5.0/helper/schema/resource.go:464 +0x390
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000350680, 0xf9b1e0, 0xc000611580, 0xc00046cfa0, 0xc000611580, 0x0, 0xfa6ca0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.5.0/helper/schema/grpc_provider.go:955 +0x8cf
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ApplyResourceChange(0xc00061c740, 0xf9b1e0, 0xc000611580, 0xc00011fa40, 0xc00061c740, 0xc00058ff50, 0xc0005f2ba0)
	github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/server/server.go:332 +0xae
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0xe334a0, 0xc00061c740, 0xf9b2a0, 0xc00058ff50, 0xc00071f1a0, 0x0, 0xf9b2a0, 0xc00058ff50, 0xc0006ee800, 0x3a2)
	github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0003968c0, 0xfa4b20, 0xc000652480, 0xc0005be000, 0xc00039ed80, 0x14a6c40, 0x0, 0x0, 0x0)
	google.golang.org/grpc@v1.37.0/server.go:1217 +0x522
google.golang.org/grpc.(*Server).handleStream(0xc0003968c0, 0xfa4b20, 0xc000652480, 0xc0005be000, 0x0)
	google.golang.org/grpc@v1.37.0/server.go:1540 +0xd05
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0002ea1b0, 0xc0003968c0, 0xfa4b20, 0xc000652480, 0xc0005be000)
	google.golang.org/grpc@v1.37.0/server.go:878 +0xa5
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.37.0/server.go:876 +0x1fd

Error: The terraform-provider-octopusdeploy_v0.7.32 plugin crashed!
```

**Comment by ecca** [comment]
@jbristowe Running version **0.7.33** solved the issue for me. Migrated successfully without errors from **project_id** to **owner_id**

**Comment by jbristowe** [comment]
OK to close this issue?

**Comment by ecca** [comment]
Sure, closing it 👍
