### ISSUE TITLE
Provider crashes on "octopusdeploy_machine_policy" creation

### ISSUE THREAD

**Issue by yafanasiev** [OctopusDeployLabs/terraform-provider-octopusdeploy#230]
When creating/updating `octopusdeploy_machine_policy` resource with any configuration block specified, provider crashes.

**Steps to reproduce**
1. Create a simple resource definition:

```
resource "octopusdeploy_machine_policy" "kubernetes" {
  name     = "Kubernetes"
  space_id = local.space_id

  connection_connect_timeout      = 5000000000
  connection_retry_count_limit    = 5
  connection_retry_sleep_interval = 20000000000
  connection_retry_time_limit     = 180000000000

  machine_connectivity_policy {
    machine_connectivity_behavior = "ExpectedToBeOnline"
  }
  machine_cleanup_policy {
    delete_machines_behavior         = "DeleteUnavailableMachines"
    delete_machines_elapsed_timespan = 3600000000000
  }
  machine_health_check_policy {
    health_check_type     = "OnlyConnectivity"
    health_check_interval = 15000000000
  }
  machine_update_policy {
    calamari_update_behavior = "UpdateAlways"
    tentacle_update_behavior = "NeverUpdate"
  }
}
```

2. Run `terraform apply`
3. Receive the following error:

```
╷
│ Error: Plugin did not respond
│ 
│   with octopusdeploy_machine_policy.kubernetes,
│   on infrastructure.tf line 1, in resource "octopusdeploy_machine_policy" "kubernetes":
│    1: resource "octopusdeploy_machine_policy" "kubernetes" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
Releasing state lock. This may take a few moments...

Stack trace from the terraform-provider-octopusdeploy_v0.7.55 plugin:

panic: interface conversion: interface {} is *schema.Set, not []interface {}

goroutine 98 [running]:
github.com/OctopusDeploy/terraform-provider-octopusdeploy/octopusdeploy.expandMachineCleanupPolicy(...)
        github.com/OctopusDeploy/terraform-provider-octopusdeploy/octopusdeploy/schema_machine_cleanup_policy.go:12
github.com/OctopusDeploy/terraform-provider-octopusdeploy/octopusdeploy.expandMachinePolicy(0xc000049980, 0x23)
        github.com/OctopusDeploy/terraform-provider-octopusdeploy/octopusdeploy/schema_machine_policy.go:43 +0xcb7
github.com/OctopusDeploy/terraform-provider-octopusdeploy/octopusdeploy.resourceMachinePolicyUpdate(0x1ba3c28, 0xc000b8a600, 0xc000049980, 0x19030a0, 0xc000246280, 0xc000d8b6a0, 0x15125aa, 0xc00035f300)
        github.com/OctopusDeploy/terraform-provider-octopusdeploy/octopusdeploy/resource_machine_policy.go:86 +0xf6
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0xc000461a40, 0x1ba3bb8, 0xc00011ae00, 0xc000049980, 0x19030a0, 0xc000246280, 0x0, 0x0, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/resource.go:364 +0x17f
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000461a40, 0x1ba3bb8, 0xc00011ae00, 0xc00013f420, 0xc00035f300, 0x19030a0, 0xc000246280, 0x0, 0x0, 0x0, ...)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/resource.go:464 +0x390
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00011c000, 0x1ba3bb8, 0xc00011ae00, 0xc0009336d0, 0xc00011ae00, 0x1a30fe0, 0xc00010ef00)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/grpc_provider.go:955 +0x8ef
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ApplyResourceChange(0xc000315960, 0x1ba3c60, 0xc00011ae00, 0xc00013f260, 0xc000315960, 0xc00010ef00, 0xc000a5dba0)
        github.com/hashicorp/terraform-plugin-go@v0.3.1/tfprotov5/server/server.go:332 +0xb5
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x1a30fe0, 0xc000315960, 0x1ba3c60, 0xc00010ef00, 0xc000aa8ea0, 0x0, 0x1ba3c60, 0xc00010ef00, 0xc00054e000, 0x963)
        github.com/hashicorp/terraform-plugin-go@v0.3.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000134380, 0x1baca18, 0xc000103c80, 0xc0005af560, 0xc000502b70, 0x20bfd60, 0x0, 0x0, 0x0)
        google.golang.org/grpc@v1.39.1/server.go:1293 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc000134380, 0x1baca18, 0xc000103c80, 0xc0005af560, 0x0)
        google.golang.org/grpc@v1.39.1/server.go:1618 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000412190, 0xc000134380, 0x1baca18, 0xc000103c80, 0xc0005af560)
        google.golang.org/grpc@v1.39.1/server.go:941 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.39.1/server.go:939 +0x1fd

Error: The terraform-provider-octopusdeploy_v0.7.55 plugin crashed!
```

**Expected behavior**
Provider should not crash and successfully create resource.

**Logs and other supporting information**
If I omit all the attributes except for `name` and `space_id`, policy get's created with default values (I can see them in state and Octopus UI), but attempt to modify any of them (e.g. `connection_connect_timeout`) leads to the same error.

**Environment and versions:**
- OS: `MacOS 11.3.1`
- Octopus Server Version: `2021.1.7665`
- Terraform Version: `v1.0.4`
- Octopus Terraform Provider Version: `0.7.55`

**Comment by yafanasiev** [comment]
I can confirm that it's working as expected now. Thanks @jbristowe!
