### ISSUE TITLE
Listing 'Server' as  a 'package_acquisition_location_options' value for a helm/docker feed causes a provider crash

### ISSUE THREAD

**Issue by dil-dvinnai** [OctopusDeployLabs/terraform-provider-octopusdeploy#446]
**Describe the bug**
Using v0.8.1 or the more recent v0.7.x versions, creating a helm or docker feed with `package_acquisition_location_options` having `Server` in the list, causes a provider crash for any subsequent `terraform apply` runs. The initial feed creation completes without error.

**Steps to reproduce**
1. Create a helm feed with `package_acquisition_location_options = ["Server"]`, e.g.:
```
resource "octopusdeploy_helm_feed" "example_helm" {
  feed_uri = "https://feed-link"
  password = "test-test-password"
  name     = "Test Helm Feed"
  username = "test-user"
  package_acquisition_location_options = ["Server"]
}
```
3. run `terraform plan`
4. run `terraform apply` , the feed gets created
5. run `terraform plan` again, notice that the `Server` location option is now planned to be added
```
      ~ package_acquisition_location_options = [
          - "ExecutionTarget",
          - "NotAcquired",
          + "Server",
        ]
```
6. run `terraform apply` again, provider crashes with the error below

**Expected behavior**
If this `package_acquisition_location_options` value is not supported for helm and docker, a more user-friendly error with a list of supported fields in the provider documentation would be helpful, or if this isn't the intended behavior, the tf apply should work.

**Logs and other supporting information**
tf plan output
```
Stack trace from the terraform-provider-octopusdeploy_v0.8.1.exe plugin:

panic: interface conversion: feeds.IFeed is *feeds.FeedResource, not *feeds.HelmFeed

goroutine 15 [running]:
github.com/OctopusDeploy/terraform-provider-octopusdeploy/octopusdeploy.resourceHelmFeedUpdate({0x1a9c288, 0xc0006d0900}, 0xc000098e00, {0x17a3f00?, 0xc000424f00})
        github.com/OctopusDeploy/terraform-provider-octopusdeploy/octopusdeploy/resource_helm_feed.go:102 +0x318
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0xc000272ee0, {0x1a9c2c0, 0xc0008fec00}, 0xd?, {0x17a3f00, 0xc000424f00})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.20.0/helper/schema/resource.go:741 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000272ee0, {0x1a9c2c0, 0xc0008fec00}, 0xc0004075f0, 0xc000098c80, {0x17a3f00, 0xc000424f00})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.20.0/helper/schema/resource.go:847 +0x83a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00059a030, {0x1a9c2c0?, 0xc0008feae0?}, 0xc0007622d0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.20.0/helper/schema/grpc_provider.go:1021 +0xe8d
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0003f4000, {0x1a9c2c0?, 0xc0008fe2a0?}, 0xc0003ee150)
        github.com/hashicorp/terraform-plugin-go@v0.13.0/tfprotov5/tf5server/server.go:813 +0x4fc
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x18e1420?, 0xc0003f4000}, {0x1a9c2c0, 0xc0008fe2a0}, 0xc0003ee000, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.13.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000dc000, {0x1aa11f8, 0xc000481ba0}, 0xc000784000, 0xc000701f50, 0x2078b00, 0x0)
        google.golang.org/grpc@v1.48.0/server.go:1295 +0xb2b
google.golang.org/grpc.(*Server).handleStream(0xc0000dc000, {0x1aa11f8, 0xc000481ba0}, 0xc000784000, 0x0)
        google.golang.org/grpc@v1.48.0/server.go:1636 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.48.0/server.go:932 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.48.0/server.go:930 +0x28a

Error: The terraform-provider-octopusdeploy_v0.8.1.exe plugin crashed!
```

**Screenshots**

**Environment and versions:**
- OS: `Windows 10`
- Octopus Server Version: `v2022.2 (Build 6910)`
- Terraform Version: `v1.1.2`
- Octopus Terraform Provider Version: [e.g. `0.8.1`]

**Additional context**
N/A

**Comment by borland** [comment]
Hi @dil-dvinnai 

`package_acquisition_location_options` should not exist on the `octopusdeploy_help_feed` resource type.
This is a bug, this is not a valid configuration option for a feed, we will remove it in the next release
