### ISSUE TITLE
Updating a helm feed crashes

### ISSUE THREAD

**Issue by millerjn21** [OctopusDeployLabs/terraform-provider-octopusdeploy#447]
**Describe the bug**
Updating an existing helm feed crashes.

**Steps to reproduce**
1. Add a helm feed to main.tf
2. run terraform apply
3. change the name of the helm feed in main.tf
4. run terraform apply
5. see error

**Expected behavior**
It to update the helm feed

**Logs and other supporting information**
```
octopusdeploy_helm_feed.example: Modifying... [id=Feeds-1607]
╷
│ Error: Plugin did not respond
│
│   with octopusdeploy_helm_feed.example,
│   on main.tf line 29, in resource "octopusdeploy_helm_feed" "example":
│   29: resource "octopusdeploy_helm_feed" "example" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The
│ plugin logs may contain more details.
╵

Stack trace from the terraform-provider-octopusdeploy_v0.8.1.exe plugin:

panic: interface conversion: feeds.IFeed is *feeds.FeedResource, not *feeds.HelmFeed

goroutine 24 [running]:
github.com/OctopusDeploy/terraform-provider-octopusdeploy/octopusdeploy.resourceHelmFeedUpdate({0x135c288, 0xc000996a80}, 0xc00055cc00, {0x1063f00?, 0xc00033c280})
        github.com/OctopusDeploy/terraform-provider-octopusdeploy/octopusdeploy/resource_helm_feed.go:102 +0x318
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0xc000780620, {0x135c2c0, 0xc000d88b40}, 0xd?, {0x1063f00, 0xc00033c280})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.20.0/helper/schema/resource.go:741 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000780620, {0x135c2c0, 0xc000d88b40}, 0xc000682000, 0xc00055ca80, {0x1063f00, 0xc00033c280})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.20.0/helper/schema/resource.go:847 +0x83a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0005154a0, {0x135c2c0?, 0xc000d88a20?}, 0xc000090460)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.20.0/helper/schema/grpc_provider.go:1021 +0xe8d
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc000000000, {0x135c2c0?, 0xc000d881e0?}, 0xc0001d41c0)
        github.com/hashicorp/terraform-plugin-go@v0.13.0/tfprotov5/tf5server/server.go:813 +0x4fc
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x11a1420?, 0xc000000000}, {0x135c2c0, 0xc000d881e0}, 0xc0001d40e0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.13.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000098000, {0x13611f8, 0xc000075860}, 0xc000d8e000, 0xc00061c4e0, 0x1938b00, 0x0)
        google.golang.org/grpc@v1.48.0/server.go:1295 +0xb2b
google.golang.org/grpc.(*Server).handleStream(0xc000098000, {0x13611f8, 0xc000075860}, 0xc000d8e000, 0x0)
        google.golang.org/grpc@v1.48.0/server.go:1636 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.48.0/server.go:932 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.48.0/server.go:930 +0x28a

Error: The terraform-provider-octopusdeploy_v0.8.1.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Environment and versions:**
- OS: windows
- Octopus Server Version: 2022.2.6971
- Terraform Version: 1.1.9
- Octopus Terraform Provider Version: 0.8.1

**Additional context**
Slack convo: (INTERNAL) https://octopusdeploy.slack.com/archives/C02A2SJ1ZFA/p1664477831346939

**Comment by jfield** [comment]
Hi, 

Is there any update on this issue? It is still a problem for us

**Comment by millerjn21** [comment]
@jbristowe . Not sure if you have notifications on this.

**Comment by jbristowe** [comment]
Looks like an easy fix. Apologies for the delay.
