### ISSUE TITLE
Crash in apply_terraform_template_action 

### ISSUE THREAD

**Issue by ryancocksbcg** [OctopusDeployLabs/terraform-provider-octopusdeploy#451]
**Describe the bug**
I get the following crash message when running terraform apply, terraform plan works fine.

**Steps to reproduce**

Run terraform apply

**Expected behavior**

**Logs and other supporting information**

Code for the step:

```
  step {
    condition           = "Success"
    name                = "Terraform Plan"
    package_requirement = "LetOctopusDecide"
    start_trigger       = "StartAfterPrevious"
    apply_terraform_template_action {
      can_be_used_for_project_versioning = false
      condition                          = "Success"
      is_disabled                        = false
      is_required                        = true
      name                               = "Terraform template action"
      run_on_server                      = true
      environments                       = var.environments
      aws_account {
        region   = "us-east-1"
        variable = octopusdeploy_variable.amazon_web_services_account_variable.id
      }

      advanced_options {
        allow_additional_plugin_downloads = false
      }
      primary_package {
        acquisition_location = "Server"
        package_id           = var.package_id

        properties = {
          "Extract" = "True"
        }
      }
    }
  }
```

Output: 

```
module.project.octopusdeploy_deployment_process.default: Modifying... [id=deploymentprocess-Projects-1381]
╷
│ Error: Request cancelled
│ 
│   with module.project.octopusdeploy_deployment_process.default,
│   on modules/projects/datadog_dashboards/octopusdeploy_deployment_process.tf line 3, in resource "octopusdeploy_deployment_process" "default":
│    3: resource "octopusdeploy_deployment_process" "default" {
│ 
│ The plugin.(*GRPCProvider).ApplyResourceChange request was cancelled.
╵

Stack trace from the terraform-provider-octopusdeploy_v0.8.1 plugin:

panic: runtime error: index out of range [0] with length 0

goroutine 75 [running]:
github.com/OctopusDeploy/terraform-provider-octopusdeploy/octopusdeploy.expandApplyTerraformTemplateAction(0x18fcce0?)
	github.com/OctopusDeploy/terraform-provider-octopusdeploy/octopusdeploy/schema_action_apply_terraform_template.go:222 +0x21d1
github.com/OctopusDeploy/terraform-provider-octopusdeploy/octopusdeploy.expandDeploymentStep(0x1994540?)
	github.com/OctopusDeploy/terraform-provider-octopusdeploy/octopusdeploy/schema_deployment_step.go:61 +0xe85
github.com/OctopusDeploy/terraform-provider-octopusdeploy/octopusdeploy.expandDeploymentProcess(0xc000afa500, 0xc0000b2280)
	github.com/OctopusDeploy/terraform-provider-octopusdeploy/octopusdeploy/schema_deployment_process.go:46 +0x4a5
github.com/OctopusDeploy/terraform-provider-octopusdeploy/octopusdeploy.resourceDeploymentProcessUpdate({0x1b800a8, 0xc00071dda0}, 0xc000afa500, {0x188eae0?, 0xc0000b2280})
	github.com/OctopusDeploy/terraform-provider-octopusdeploy/octopusdeploy/resource_deployment_process.go:201 +0x171
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0xc0008000e0, {0x1b800e0, 0xc000b1e480}, 0xd?, {0x188eae0, 0xc0000b2280})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.20.0/helper/schema/resource.go:741 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0008000e0, {0x1b800e0, 0xc000b1e480}, 0xc000b5ad00, 0xc000ba2600, {0x188eae0, 0xc0000b2280})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.20.0/helper/schema/resource.go:847 +0x83a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0000d6018, {0x1b800e0?, 0xc000b1e360?}, 0xc000bb8500)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.20.0/helper/schema/grpc_provider.go:1021 +0xe8d
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0000bc000, {0x1b800e0?, 0xc000e65d10?}, 0xc0003a82a0)
	github.com/hashicorp/terraform-plugin-go@v0.13.0/tfprotov5/tf5server/server.go:813 +0x4fc
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x19cb5a0?, 0xc0000bc000}, {0x1b800e0, 0xc000e65d10}, 0xc0003a8230, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.13.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000363c0, {0x1b85098, 0xc0005016c0}, 0xc000bb6d80, 0xc00042bc50, 0x2157c40, 0x0)
	google.golang.org/grpc@v1.48.0/server.go:1295 +0xb2b
google.golang.org/grpc.(*Server).handleStream(0xc0000363c0, {0x1b85098, 0xc0005016c0}, 0xc000bb6d80, 0x0)
	google.golang.org/grpc@v1.48.0/server.go:1636 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.48.0/server.go:932 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.48.0/server.go:930 +0x28a

Error: The terraform-provider-octopusdeploy_v0.8.1 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Screenshots**

**Environment and versions:**
- OS: `OSX`
- Octopus Server Version: https://octopus.com/downloads/2022.4.2898-hotfix.3688
- Terraform Version: v1.3.0
- Octopus Terraform Provider Version: 0.8.1

**Additional context**
The tf applies cleanly with the `apply_terraform_template_action` step removed.

**Comment by andrew22224** [comment]
not sure if this will fix this issue but I has this issue too on the current provider and it looks as if step.apply_terraform_template_action.template is a required block even though its not stated in the docs. 

so modifying your code to include an empty template block (like below) might resolve it like it did for me:

step {
    condition           = "Success"
    name                = "Terraform Plan"
    package_requirement = "LetOctopusDecide"
    start_trigger       = "StartAfterPrevious"
    apply_terraform_template_action {
      can_be_used_for_project_versioning = false
      condition                          = "Success"
      is_disabled                        = false
      is_required                        = true
      name                               = "Terraform template action"
      run_on_server                      = true
      environments                       = var.environments
      aws_account {
        region   = "us-east-1"
        variable = octopusdeploy_variable.amazon_web_services_account_variable.id
      }

      advanced_options {
        allow_additional_plugin_downloads = false
      }
      
      template {

      }

      primary_package {
        acquisition_location = "Server"
        package_id           = var.package_id

        properties = {
          "Extract" = "True"
        }
      }
    }
  }

**Comment by andrew22224** [comment]
@mcasperson can you confirm this is a required block with min 1

**Comment by mjhilton** [comment]
Looks like we either need to update the schema and docs to mark this required, or to go and find why things are blowing up during Create if the `template` isn't provided.

**Comment by domenicsim1** [comment]
This has been fixed in the new process resource release in v1.0.0 of the provider. Please note the following.

> On 1 June 2025, the Octopus Deploy Terraform Provider was promoted from a Labs project to a fully-supported, first-class Octopus Deploy integration.
> 
> As part of this promotion, we released [v1.0 of the provider](https://registry.terraform.io/providers/OctopusDeploy/octopusdeploy/1.0.0), and migrated the codebase from the OctopusDeployLabs GitHub organization to the OctopusDeploy organization. The provider also moved in the Hashicorp Terraform Registry.
> 
> New Repository: https://github.com/OctopusDeploy/
> New Provider Registry Page: https://registry.terraform.io/providers/OctopusDeploy/octopusdeploy/latest/docs
> Migration Guide: https://registry.terraform.io/providers/OctopusDeploy/octopusdeploy/1.0.0/docs/guides/moving-from-octopus-deploy-labs-namespace
> We are no longer accepting contributions or issues in this repo, and we plan to archive it.
> 
> Please head over to the new repository for continued support, updates and contributions.
