### ISSUE TITLE
Data resource "octopusdeploy_projects" fails when space contains both normal projects and source-controllet projects.

### ISSUE THREAD

**Issue by andrstor** [OctopusDeployLabs/terraform-provider-octopusdeploy#458]
**Describe the bug**
When using the data resource "octopusdeploy_projects" to get all projects in a space, it fails when the space contains source-controlled projects and normal projects. It works fine against a space with only normal projects.

**Steps to reproduce**
1. Create a space in Octopus with both source controlled and normal projects.
2. Use the datasource "octopusdeploy_projects" to get all projects

```hcl
data "octopusdeploy_projects" "all_projects" {
  take = "500" # take all
}
```
**Expected behavior**
Terraform gets a list of all projects from Octopus.

**Logs and other supporting information**
Terraform plan fails with:

```
│ Error: Plugin did not respond
│
│   with data.octopusdeploy_projects.all_projects,
│   on octopus.tf line 19, in data "octopusdeploy_projects" "all_projects":
│   19: data "octopusdeploy_projects" "all_projects" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadDataSource call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-octopusdeploy_v0.8.1.exe plugin:

panic: interface conversion: interface {} is nil, not string

goroutine 71 [running]:
github.com/OctopusDeploy/terraform-provider-octopusdeploy/octopusdeploy.flattenProject(0xc000594820)
        github.com/OctopusDeploy/terraform-provider-octopusdeploy/octopusdeploy/schema_project.go:148 +0x154b
github.com/OctopusDeploy/terraform-provider-octopusdeploy/octopusdeploy.dataSourceProjectsRead({0x181c2c0?, 0xc00080fe00?}, 0x0?, {0x1523f00?, 0xc00042c500})
        github.com/OctopusDeploy/terraform-provider-octopusdeploy/octopusdeploy/data_source_projects.go:40 +0x438
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc00053f420, {0x181c2c0, 0xc00080fe00}, 0xd?, {0x1523f00, 0xc00042c500})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.20.0/helper/schema/resource.go:724 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ReadDataApply(0xc00053f420, {0x181c2c0, 0xc00080fe00}, 0xc000538f00, {0x1523f00, 0xc00042c500})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.20.0/helper/schema/resource.go:943 +0x145
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadDataSource(0xc0000080c0, {0x181c2c0?, 0xc00080fce0?}, 0xc000807060)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.20.0/helper/schema/grpc_provider.go:1179 +0x38f
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadDataSource(0xc000142640, {0x181c2c0?, 0xc00080f530?}, 0xc0009c9860)
        github.com/hashicorp/terraform-plugin-go@v0.13.0/tfprotov5/tf5server/server.go:658 +0x403
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadDataSource_Handler({0x1661420?, 0xc000142640}, {0x181c2c0, 0xc00080f530}, 0xc0003f9e30, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.13.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:421 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000156000, {0x18211f8, 0xc0001056c0}, 0xc0008047e0, 0xc0006d4870, 0x1df8b30, 0x0)
        google.golang.org/grpc@v1.48.0/server.go:1295 +0xb2b
google.golang.org/grpc.(*Server).handleStream(0xc000156000, {0x18211f8, 0xc0001056c0}, 0xc0008047e0, 0x0)
        google.golang.org/grpc@v1.48.0/server.go:1636 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.48.0/server.go:932 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.48.0/server.go:930 +0x28a

Error: The terraform-provider-octopusdeploy_v0.8.1.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Environment and versions:**
- OS:Windows
- Octopus Server Version: 2022.3
- Terraform Version: 1.3.4
- Octopus Terraform Provider Version: 0.8.1

**Comment by slewis74** [comment]
Hi, just wondering if any of the source controlled projects are using the Library Git Credentials for authentication, or are they defining the username/password directly on the project settings page? If they are using the Library GitCredentials then I suspect you may be running into issues because Octopus' API changed with relation to how this data was stored. We've release an update (`0.9.0`) today that should address these issues. Would you be able to try using that version of the provider and let us know if the issue continues?

**Comment by slewis74** [comment]
Excellent, great to hear and sorry for the inconvenience.
