### ISSUE TITLE
Unable to apply a "Apply a Terraform template" step

### ISSUE THREAD

**Issue by mcasperson** [OctopusDeployLabs/terraform-provider-octopusdeploy#478]
**Describe the bug**
The Octopus Terraform Provider version 0.10.1 fails to deploy a `Apply a Terraform template` step. The example Terraform configuration file below shows the issue: 

```
terraform {

  required_providers {
    octopusdeploy = { source = "OctopusDeployLabs/octopusdeploy", version = "0.10.1"}
  }
}

variable "octopus_server" {
  type        = string
  nullable    = false
  sensitive   = false
  description = "The URL of the Octopus server e.g. https://myinstance.octopus.app."
}
variable "octopus_apikey" {
  type        = string
  nullable    = false
  sensitive   = true
  description = "The API key used to access the Octopus server. See https://octopus.com/docs/octopus-rest-api/how-to-create-an-api-key for details on creating an API key."
}
variable "octopus_space_id" {
  type        = string
  nullable    = false
  sensitive   = false
  description = "The ID of the Octopus space to populate."
}

provider "octopusdeploy" {
  address  = "${var.octopus_server}"
  api_key  = "${var.octopus_apikey}"
  space_id = "${var.octopus_space_id}"
}

data "octopusdeploy_project_groups" "project_group_default_project_group" {
  ids          = null
  partial_name = "Default Project Group"
  skip         = 0
  take         = 1
}

data "octopusdeploy_lifecycles" "lifecycle_default_lifecycle" {
  ids          = null
  partial_name = "Default Lifecycle"
  skip         = 0
  take         = 1
}

resource "octopusdeploy_project" "project_terraform_demo" {
  name                                 = "Terraform Demo"
  auto_create_release                  = false
  default_guided_failure_mode          = "EnvironmentDefault"
  default_to_skip_if_already_installed = false
  description                          = ""
  discrete_channel_release             = false
  is_disabled                          = false
  is_version_controlled                = false
  project_group_id                     = "${data.octopusdeploy_project_groups.project_group_default_project_group.project_groups[0].id}"
  lifecycle_id                         = "${data.octopusdeploy_lifecycles.lifecycle_default_lifecycle.lifecycles[0].id}"
  included_library_variable_sets       = []
  tenanted_deployment_participation    = "Untenanted"

  connectivity_policy {
    allow_deployments_to_no_targets = true
    exclude_unhealthy_targets       = false
    skip_machine_behavior           = "None"
  }
}

resource "octopusdeploy_deployment_process" "deployment_process_project_terraform_demo" {
  project_id = "${octopusdeploy_project.project_terraform_demo.id}"

  step {
    condition           = "Success"
    name                = "Apply a Terraform template"
    package_requirement = "LetOctopusDecide"
    start_trigger       = "StartAfterPrevious"

    action {
      action_type                        = "Octopus.TerraformApply"
      name                               = "Apply a Terraform template"
      condition                          = "Success"
      run_on_server                      = true
      is_disabled                        = false
      can_be_used_for_project_versioning = false
      is_required                        = false
      worker_pool_id                     = ""
      worker_pool_variable               = ""
      properties                         = { "Octopus.Action.GoogleCloud.ImpersonateServiceAccount" = "False", "Octopus.Action.GoogleCloud.UseVMServiceAccount" = "True", "Octopus.Action.Script.ScriptSource" = "Inline", "Octopus.Action.Terraform.AllowPluginDownloads" = "True", "Octopus.Action.Terraform.AzureAccount" = "False", "Octopus.Action.Terraform.GoogleCloudAccount" = "False", "Octopus.Action.Terraform.ManagedAccount" = "None", "Octopus.Action.Terraform.PlanJsonOutput" = "False", "Octopus.Action.Terraform.RunAutomaticFileSubstitution" = "True", "Octopus.Action.Terraform.Template" = "#test", "Octopus.Action.Terraform.TemplateParameters" = "{}" }
      environments                       = []
      excluded_environments              = []
      channels                           = []
      tenant_tags                        = []
      features                           = []
    }

    properties   = {}
    target_roles = []
  }
}
```

The error is shown below:

``` 
│ Error: Request cancelled
│ 
│   with octopusdeploy_deployment_process.deployment_process_project_terraform_demo,
│   on octopus.tf line 68, in resource "octopusdeploy_deployment_process" "deployment_process_project_terraform_demo":
│   68: resource "octopusdeploy_deployment_process" "deployment_process_project_terraform_demo" {
│ 
│ The plugin.(*GRPCProvider).ApplyResourceChange request was cancelled.
╵

Stack trace from the terraform-provider-octopusdeploy_v0.10.1 plugin:

panic: interface conversion: interface {} is string, not *schema.Set

goroutine 108 [running]:
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).setSet(0xc00089f008, {0xc000fa8a00, 0x5, 0x5}, {0xcdb5e0, 0xc000c8b1b0}, 0xc000847cc0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/field_writer_map.go:343 +0x7b4
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).set(0xc00089f008, {0xc000fa8a00, 0x5, 0x5}, {0xcdb5e0, 0xc000c8b1b0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/field_writer_map.go:107 +0x14c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).setObject(0xc000b26100?, {0xc000b26100?, 0x4, 0x4}, {0xd1dc80, 0xc000568270})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/field_writer_map.go:222 +0x312
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).set(0xc00089f008, {0xc000b26100, 0x4, 0x4}, {0xd1dc80, 0xc000568270})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/field_writer_map.go:109 +0x11c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).setList.func1(...)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/field_writer_map.go:122
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).setList(0xc00089f008, {0xc000568420?, 0x3, 0x3}, {0xcc9560, 0xc0001da870})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/field_writer_map.go:142 +0x52a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).set(0xc00089f008, {0xc000568420, 0x3, 0x3}, {0xcc9560, 0xc0001da870})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/field_writer_map.go:103 +0xa5
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).setObject(0xc00043a0c0?, {0xc00043a0c0?, 0x2, 0x2}, {0xd1dc80, 0xc000568240})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/field_writer_map.go:222 +0x312
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).set(0xc00089f008, {0xc00043a0c0, 0x2, 0x2}, {0xd1dc80, 0xc000568240})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/field_writer_map.go:109 +0x11c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).setList.func1(...)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/field_writer_map.go:122
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).setList(0xc00089f008, {0xc000c8b1f0?, 0x1, 0x1}, {0xcc9a60, 0xc0001da888})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/field_writer_map.go:142 +0x52a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).set(0xc00089f008, {0xc000c8b1f0, 0x1, 0x1}, {0xcc9a60, 0xc0001da888})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/field_writer_map.go:103 +0xa5
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).WriteField(0xc00089f008, {0xc000c8b1f0, 0x1, 0x1}, {0xcc9a60, 0xc0001da888})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/field_writer_map.go:89 +0x3f9
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).Set(0xc0001e4180, {0xe31920, 0x4}, {0xcc9a60, 0xc0001da888})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource_data.go:227 +0x210
github.com/OctopusDeploy/terraform-provider-octopusdeploy/octopusdeploy.setDeploymentProcess({0xc000ae61c0?, 0xc000bd4990?}, 0x1f?, 0xc00056d4d0)
	github.com/OctopusDeploy/terraform-provider-octopusdeploy/octopusdeploy/schema_deployment_process.go:61 +0x151
github.com/OctopusDeploy/terraform-provider-octopusdeploy/octopusdeploy.resourceDeploymentProcessCreate({0xfab508, 0xc00073f920}, 0xc0001e4180, {0xd3d920?, 0xc000002580})
	github.com/OctopusDeploy/terraform-provider-octopusdeploy/octopusdeploy/resource_deployment_process.go:91 +0x305
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc0001c6c40, {0xfab540, 0xc000e70d80}, 0xd?, {0xd3d920, 0xc000002580})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:707 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0001c6c40, {0xfab540, 0xc000e70d80}, 0xc000e93c70, 0xc0004d8c00, {0xd3d920, 0xc000002580})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:837 +0xa85
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0000e4948, {0xfab540?, 0xc000e70c60?}, 0xc000d89810)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/grpc_provider.go:1021 +0xe8d
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc00078c000, {0xfab540?, 0xc000e70630?}, 0xc0007811f0)
	github.com/hashicorp/terraform-plugin-go@v0.14.2/tfprotov5/tf5server/server.go:818 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xdef4e0?, 0xc00078c000}, {0xfab540, 0xc000e70630}, 0xc000781180, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.14.2/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000f8000, {0xfb06c0, 0xc0006824e0}, 0xc000e75560, 0xc00088a300, 0x15970c0, 0x0)
	google.golang.org/grpc@v1.51.0/server.go:1340 +0xd23
google.golang.org/grpc.(*Server).handleStream(0xc0000f8000, {0xfb06c0, 0xc0006824e0}, 0xc000e75560, 0x0)
	google.golang.org/grpc@v1.51.0/server.go:1713 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.51.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.51.0/server.go:963 +0x28a

Error: The terraform-provider-octopusdeploy_v0.10.1 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

```

**Steps to reproduce**
1. Save the example Terraform configuration to a file called `octopus.tf`
2. Run `terraform init` and `terraform apply -var=octopus_server=https://yourinstance.octopus.app -var=octopus_apikey=API-ABCDEFGHIJKLMNOP -var=octopus_space_id=Spaces-1 -auto-approve`
3. See the error

**Expected behavior**
The `Apply a Terraform template` step should be created in the target space.

**Environment and versions:**
- OS: `Linux`
- Octopus Server Version: Ubuntu 22.04.1
- Terraform Version: 1.3.7
- Octopus Terraform Provider Version: 0.10.1

**Additional context**

**Comment by mcasperson** [comment]
I suspect the issue is due to this [line of code](https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/blob/main/octopusdeploy/schema_action_apply_terraform_template.go#L509) that sets `flattenedAction["template"] = v.Value`:

```
	for k, v := range action.Properties {
		switch k {
		case "Octopus.Action.RunOnServer":
			runOnServer, _ := strconv.ParseBool(v.Value)
			flattenedAction["run_on_server"] = runOnServer
		case "Octopus.Action.Script.ScriptSource":
			if v.Value == "Package" {
				flattenedAction["template"] = flattenTerraformTemplate(action.Properties)
			}
		case "Octopus.Action.Terraform.AzureAccount":
			if v.Value == "True" {
				flattenedAction["azure_account"] = flattenTerraformTemplateAzureAccount(action.Properties)
			}
		case "Octopus.Action.Terraform.GoogleCloudAccount":
			if v.Value == "True" {
				flattenedAction["google_cloud_account"] = flattenTerraformTemplateGoogleAccount(action.Properties)
			}
		case "Octopus.Action.Terraform.ManagedAccount":
			if v.Value == "AWS" {
				flattenedAction["aws_account"] = flattenTerraformTemplateAwsAccount(action.Properties)
			}
		case "Octopus.Action.Terraform.Template":
			flattenedAction["template"] = v.Value
		case "Octopus.Action.Terraform.TemplateParameters":
			flattenedAction["template_parameters"] = v.Value
		}
	}
```
The schema for `template` [is defined as a Set](https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/blob/main/octopusdeploy/schema_action_apply_terraform_template.go#L166) in the `addTerraformTemplateSchema` function. But the code above is attempting to assign a string value to the `template` field for an inline Terraform template.

The step is applied correctly if [this case statement](https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/blob/main/octopusdeploy/schema_deployment_step.go#L142) is removed, which means the action is treated as a plain action.
