### ISSUE TITLE
Cannot create octopusdeploy_project with git_username_password_persistence_settings

### ISSUE THREAD

**Issue by JakeBarbieur-Zywave** [OctopusDeployLabs/terraform-provider-octopusdeploy#787]
**Describe the bug**

**Steps to reproduce**

1. Write Terraform to create a new octopusdeploy_project using a git_username_password_persistence_settings block and attempt to apply it.  

Example code:

`terraform {
  required_version = ">= 1.1.7"
  required_providers {
    octopusdeploy = {
      source  = "OctopusDeployLabs/octopusdeploy"
      version = "0.30.6"
    }
  }
}

provider "octopusdeploy" {
  address  = var.octopus_address
  api_key  = var.octopus_api_key
  space_id = var.space_id
}

variable "octopus_address" {
  default = "https://exp-octopus.ourdomain.com"
}
variable "octopus_api_key" {
  default = "API-KEY"
}
variable "space_id" {
  default = "Spaces-3"
}

variable "git_username" {
  default = "git-token"
}
variable "git_password" {
  default = "gitlab_token"
}

resource "octopusdeploy_project" "this" {

  name                           = "Harbor"
  description                    = ""
  lifecycle_id                   = "Lifecycles-62"
  project_group_id               = "ProjectGroups-102"
  is_disabled                    = false
  is_version_controlled          = true
  included_library_variable_sets = []
  git_username_password_persistence_settings {
    url            = "https://gitlab.com/our_project.git"
    default_branch = "main"
    base_path      = ".octopus/harbor"
    username       = var.git_username
    password       = var.git_password
  }
}
`

**Expected behavior**
Project would be created/updated if it already exists.

**Actual behavior**
The following error is produced:
`│ Error: Error converting project to VCS
│
│   with octopusdeploy_project.this,
│   on main.tf line 34, in resource "octopusdeploy_project" "this":
│   34: resource "octopusdeploy_project" "this" {
│
│ Octopus API error: There was a problem with your request. [Value cannot be null. (Parameter 'source')]
`

**Logs and other supporting information**

TF Plan:
` terraform plan

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # octopusdeploy_project.this will be created
  + resource "octopusdeploy_project" "this" {
      + auto_create_release                  = (known after apply)
      + default_guided_failure_mode          = (known after apply)
      + default_to_skip_if_already_installed = (known after apply)
      + deployment_changes_template          = (known after apply)
      + deployment_process_id                = (known after apply)
      + discrete_channel_release             = (known after apply)
      + id                                   = (known after apply)
      + included_library_variable_sets       = []
      + is_disabled                          = false
      + is_discrete_channel_release          = (known after apply)
      + is_version_controlled                = true
      + lifecycle_id                         = "Lifecycles-62"
      + name                                 = "Harbor"
      + project_group_id                     = "ProjectGroups-102"
      + release_notes_template               = (known after apply)
      + slug                                 = (known after apply)
      + space_id                             = (known after apply)
      + tenanted_deployment_participation    = (known after apply)
      + variable_set_id                      = (known after apply)

      + git_username_password_persistence_settings {
          + base_path      = ".octopus/harbor"
          + default_branch = "main"
          + password       = (sensitive value)
          + url            = "https://gitlab.com/our_project.git"
          + username       = "git-token"
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

`

TF Apply produces the error mentioned above.

Octopus server logs:
`Unhandled error on request: "Value cannot be null. (Parameter 'source')" System.ArgumentNullException: Value cannot be null. (Parameter 'source')
     at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
     at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
     at Octopus.Core.Model.Projects.GitPersistenceSettings.IsProtectedBranch(GitBranch branch) in ./source/Octopus.Core/Model/Projects/GitPersistenceSettings.cs:line 77
at Octopus.Core.Git.Transactions.GitDocumentTransaction.EnsureBranchIsNotProtected(GitBranch gitBranch) in ./source/Octopus.Core/Git/Transactions/GitDocumentTransaction.cs:line 168
   at Octopus.Core.Git.Transactions.GitDocumentTransaction.GetValidatedBranch() in ./source/Octopus.Core/Git/Transactions/GitDocumentTransaction.cs:line 238
   at Octopus.Core.Git.Transactions.GitDocumentTransaction.<>c__DisplayClass18_0.<<Commit>b__0>d.MoveNext() in ./source/Octopus.Core/Git/Transactions/GitDocumentTransaction.cs:line 139
--- End of stack trace from previous location ---
     at Octopus.Core.Git.Transactions.GitDocumentTransaction.MigrateBeforeExecute[T](Func`1 innerOperation, CancellationToken cancellationToken)
     at Octopus.Core.Git.Transactions.GitDocumentTransaction.Commit(String message, CancellationToken cancellationToken) in ./source/Octopus.Core/Git/Transactions/GitDocumentTransaction.cs:line 135
     at Octopus.Core.Infrastructure.UnitsOfWork.UnitOfWork.CommitToGit(CancellationToken cancellationToken) in ./source/Octopus.Core/Infrastructure/UnitsOfWork/UnitOfWork.cs:line 198
at Octopus.Core.Infrastructure.UnitsOfWork.UnitOfWork.Complete(CancellationToken cancellationToken) in ./source/Octopus.Core/Infrastructure/UnitsOfWork/UnitOfWork.cs:line 110
   at Octopus.Server.Web.Middleware.ActionFilters.UnitOfWorkActionFilter.OnActionExecutionAsync(ActionExecutingContext context, ActionExecutionDelegate next) in ./source/Octopus.Server/Web/Middleware/ActionFilters/UnitOfWorkActionFilter.cs:line 27
   at
at Octopus.Server.Web.Middleware.ActionFilters.UnitOfWorkActionFilter.OnActionExecutionAsync(ActionExecutingContext context, ActionExecutionDelegate next) in ./source/Octopus.Server/Web/Middleware/ActionFilters/UnitOfWorkActionFilter.cs:line 32
     at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
     at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
     at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
t Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
     at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
     at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
     at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
t Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|7_0(Endpoint endpoint, Task requestTask, ILogger logger)
     at Octopus.Server.Web.Middleware.BoundaryTrailerRewriteMiddleware.Invoke(HttpContext context, IAutomationContext automationContext) in ./source/Octopus.Server/Web/Middleware/BoundaryTrailerRewriteMiddleware.cs:line 45
     at Octopus.Server.Web.Infrastructure.Authentication.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult) in ./source/Octopus.Server/Web/Infrastructure/Authentication/AuthorizationMiddlewareResultHandler.cs:line 50
     at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
     at Octopus.Server.Web.UnitOfWorkMiddleware.InvokeAsync(HttpContext httpContext, IUnitOfWork unitOfWork) in ./source/Octopus.Server/Web/UnitOfWorkMiddleware.cs:line 31
     at Octopus.Server.Web.UnitOfWorkMiddleware.InvokeAsync(HttpContext httpContext, IUnitOfWork unitOfWork) in ./source/Octopus.Server/Web/UnitOfWorkMiddleware.cs:line 42
     at Octopus.Server.Web.Middleware.OctopusClientOldVersionWarningMiddleware.InvokeAsync(HttpContext context, IAutomationContext automationContext) in ./source/Octopus.Server/Web/Middleware/OctopusClientOldVersionWarningMiddleware.cs:line 24
at Octopus.Server.Web.Middleware.DynamicContentHeadersMiddleware.InvokeAsync(HttpContext context) in ./source/Octopus.Server/Web/Middleware/DynamicContentHeadersMiddleware.cs:line 50
     at Octopus.Server.Web.Middleware.MaintenanceModeMiddleware.InvokeAsync(HttpContext context) in ./source/Octopus.Server/Web/Middleware/MaintenanceModeMiddleware.cs:line 58
     at Octopus.Server.Web.Middleware.OctopusAuthenticationMiddleware.InvokeAsync(HttpContext context, IUserAuthenticator userAuthenticator, IUserSessionService userSessionService, IWebAuthCache authCache, ILogger logger) in ./source/Octopus.Server/Web/Middleware/OctopusAuthenticationMiddleware.cs:line 61
     at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Octopus.Server.Web.Middleware.TelemetryMiddleware.InvokeAsync(HttpContext context) in ./source/Octopus.Server/Web/Middleware/TelemetryMiddleware.cs:line 64
   at Octopus.Server.Web.Middleware.ErrorHandlingMiddleware.InvokeAsync(HttpContext context) in ./source/Octopus.Server/Web/Middleware/ErrorHandlingMiddleware.cs:line 51
`

**Environment and versions:**
- OS: Windows
- Octopus Server Version: 2024.2 Build 9441
- Terraform Version: 1.9.6
- Octopus Terraform Provider Version: 0.30.6

**Additional context**
It appears this behavior was introduced between 0.30.0-beta1 and 0.30.0-beta2 versions of the octopusdeploy provider.

**Comment by mik-ky** [comment]
From my testing, this broke between versions v0.23.1 and v0.30.0.

Workaround would be to specify the `protected_branches` in the git_username_password_persistence_settings [schema](https://registry.terraform.io/providers/OctopusDeployLabs/octopusdeploy/latest/docs/resources/project#nested-schema-for-git_username_password_persistence_settings) explicitly until it's fixed.

**Comment by mjhilton** [comment]
This is fixed in [Release v0.40.0](https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/releases/tag/v0.40.0)
